[package]
name    = "hello"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies.linux-std]
path = "std"

[dependencies]
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }

