[package]
name    = "linux-std"
version = "0.1.0"

# Generate bindings for kernel functions
build = "build.rs"

[build-dependencies]
bindgen = {git = "https://github.com/servo/rust-bindgen.git"}
shlex   = "0.1.*"
